# Generated by Django 4.1.3 on 2022-11-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=1)),
                ("date", models.CharField(max_length=8)),
                ("valor", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=11)),
                ("hour", models.CharField(max_length=6)),
                ("owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
            ],
        ),
    ]
